remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


title: ðŸ‘‹ Welcome to my <code>Data Portfolio</code>
description: Data Engineer | B.S. Software Engineering (In Progress) | 5+ Years in Analytics
