remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


title: ðŸ‘‹ Welcome to my <code>Data Portfolio</code>
description: Find me on LinkedIn
linkedin_url: https://www.linkedin.com/in/cameron-css
