remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


title: ðŸ‘‹ Welcome to my <code>Data Portfolio</code>
description: [Find me on [LinkedIn](https://www.linkedin.com/in/cameron-css) [<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1200px-LinkedIn_icon.svg.png" alt="LinkedIn" width="20"/>](https://www.linkedin.com/in/cameron-css)]
